### PR TITLE
build: remove `vue-router` auto import type & upgrade deps

### PR DESCRIPTION
**Pull request by yuler**
## Updates

- degrade @vueuse/core to 5.x

    > From v6.0, VueUse requires vue >= v3.2 or @vue/composition-api >= v1.1

    refs: https://vueuse.org/guide/

- remove `vue-router` auto import in vite.config.js

    It will auto import `useRoute` & `useRouter`, but it doesn't exist in vue-router@3.x

- refresh `yarn.lock` & `auto-imports.d.ts`

### CODE REVIEW

**Comment by lstoeferle** [comment]
Hey @yuler,
good catch with the `vue-router` auto-imports. But there is one thing I did not get, why you want to degrade `@vueuse/core` to v5? This project is using `@vue/composition-api` v1.4 which is meeting the requirements.

Please revert your changes related to `@vueuse/core` and we can merge your PR :)

**Comment by yuler** [comment]
@lstoeferle 

degrade `@vueuse/core` to  v5.x because I see

> From v6.0, VueUse requires vue >= v3.2 or @vue/composition-api >= v1.1

In the [official website](https://vueuse.org/guide/#:~:text=From%20v6.0%2C%20VueUse%20requires%20vue%20%3E%3D%20v3.2%20or%20%40vue/composition%2Dapi%20%3E%3D%20v1.1)

**Comment by yuler** [comment]
Sorry, I misunderstand.

It's **or**

**Comment by yuler** [comment]
@lstoeferle 

Hi, I backup to `@vueuse/core` & upgrade `@vue/composition-api`

**Comment by lstoeferle** [comment]
Thanks 😉

**Pull request merged**
